config/routes.rb
Tp::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registration' }

  
  get "/" => 'contracts#index'

  get "people/search" => 'people#search'
  get ':controller/validate', action: 'validate', as: :validate_form
  get "people/get_new_view" => 'people#get_new_view'
  get "organizations/search" => 'organizations#search'
  post "contracts/save_filter" => 'contracts#save_filter'
  post "contracts/clear_filter" => 'contracts#clear_filter'
  get "contracts/print/:id" => 'contracts#print', as: :contract_print
  resources :contracts
  resources :organizations
  resources :people
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  include Filterable
  include I18n::Alchemy
  
  belongs_to :insurant
  belongs_to :insured
  belongs_to :user, foreign_key: 'agent_id'
  
  validates :number, presence:true, uniqueness: true
  validates :insurant_id, presence:true
  validates :insured_id, presence: true
  
  scope :fnumber, ->(f) {where("number like ?","%#{f}%")}
  scope :fdate_f, ->(d) {where("date >= ?", d)}
  scope :fdate_l, ->(d) {where("date <= ?", d)}
  scope :fdatestart_f, ->(d) {where("datestart >= ?", d)}
  scope :fdatestart_l, ->(d) {where("datestart <= ?", d)}
  scope :fdatefinish_f, ->(d) {where("datefinish >= ?", d)}
  scope :fdatefinish_l, ->(d) {where("datefinish <= ?", d)}
  scope :fcost, ->(c) {where("cost = ?",c)}
  scope :fikp, ->(i) {where("users.ikp = ?",i)}
  scope :finsurant_name, ->(f) {where("people.firstname like :n or people.lastname like :n",n: "%#{f}%")}
  scope :finsured_name, ->(f) {where("insureds_contracts.firstname like :n or insureds_contracts.lastname like :n",n: "%#{f}%")}

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
   before_filter :authenticate_user!
  
  def index
    @session=session[:filter] ||= {}
    @contracts=current_user.contracts
            .joins(:insurant,:insured,:user)
            .filter(@session)
            .paginate(page: params[:page], per_page: 10)
  end
  
  def print
    @contract=current_user.contracts.find(params[:id])
    render 'edit'
  end

  def new
    @contract=current_user.contracts.new
    @contract.number=(Contract.last.number.to_i+1).to_s
    #@contract.build_insurant
    #@contract.insurant.build_organization
    #@contract.build_insured
    @organizations=Organization.all
    
  end
  
  def create
    @contract=current_user.contracts.new(contract_params)

    if @contract.save
      flash[:success]= t(:contract_added)
      #redirect_to(contracts_path)
      contractnew=current_user.contracts.new
      contractnew.number=(@contract.number.to_i+1).to_s
      contractnew.date=@contract.date
      contractnew.datestart=@contract.datestart
      contractnew.datefinish=@contract.datefinish
      contractnew.cost=@contract.cost
      contractnew.insurant_id=@contract.insurant_id
      @contract=contractnew
    end
    @organizations=Organization.all
    render 'new'
  end
  
  def edit
    @contract=current_user.contracts.find(params[:id]).localized
  end
  
  def update
    @contract=current_user.contracts.find(params[:id])
    if @contract.update_attributes(contract_params)
      flash[:success]= t(:contract_updated)
      redirect_to(contracts_path)
    else
      @organizations=Organization.all
      render 'edit'
    end
  end
  
  def destroy
    if current_user.contracts.find(params[:id]).delete
      flash[:success]='Policy deleted successfully!'
    else
      flash[:error]='Error while deleting policy'
    end
    redirect_to(contracts_path)
  end
  
  def save_filter
    session[:filter] ||= {}
    filter_params.each { |key,val| session[:filter][key]=val }
    flash[:success]='Filter updated'
    redirect_to(contracts_path)
  end
  
  def clear_filter
    session[:filter] ||= {}
    filter_arr.each { |key,val| session[:filter][key]=""}
    flash[:success]='Filter cleared'
    redirect_to(contracts_path)
  end
  
  private
  
    def contract_params
      params.require(:contract).permit(:number, :insurant_id, :insured_id, :cost, 
                                     :date, :datestart, :datefinish,
                                      insurant_attributes:[:id, :firstname, :lastname, :organization_id],
                                      insured_attributes:[:id, :firstname, :lastname])
    end
  
    def filter_params
      params.require(:filter).permit(filter_arr)
    end
    
    def filter_arr
      ["fnumber", "finsurant_name", "finsured_name", "fcost", 
       "fdate_f", "fdate_l", "fdatestart_f", "fdatestart_l",
       "fdatefinish_f", "fdatefinish_l", "fikp"]
    end
    
end

app/views/contracts/_contract.html.erb
  <tr>
    <td><%= link_to contract.number, edit_contract_path(contract) %></td>
    <td><%= contract.localized.date %></td>
    <td><%= contract.localized.datestart %></td>
    <td><%= contract.localized.datefinish %></td>
    <td><%= contract.insurant.name %></td>
    <td><%= contract.insured.name %></td>
    <td><%= contract.localized.cost %></td>
    <td><%= contract.user.ikp %></td>
    <td><%= link_to "Remove", contract, method: :delete, data: { confirm: "Are you sure?" } %>
      <%= link_to t("contract.view.index.print"), contract_print_path(contract) %></td>
  </tr>

app/views/contracts/_contract_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

  <%= f.label :number %>
  <%= f.text_field :number, tabindex: 1 %>

  <%= f.label :date %>
  <%= f.date_field :date, tabindex: 2 %>

  <%= f.label :datestart %>
  <%= f.date_field :datestart, tabindex: 3 %>

  <%= f.label :datefinish %>
  <%= f.date_field :datefinish, tabindex: 4 %>

  <%= f.label :cost %>
  <%= f.text_field :cost, tabindex: 5 %>

  <%= f.hidden_field :insurant_id %>
  <%= f.hidden_field :insured_id %>

<br />

app/views/contracts/_filter_field.erb
    <td class="filter-row">
      <% locals.each do |key,val| %>
        <div class="input-append">
          <%  if val.scan("date").size>0 %>
            <%= date_field_tag "filter[#{val}]", s["#{val}"], class: "input-small filter" %>
          <%  else %>
            <%= text_field_tag "filter[#{val}]", s["#{val}"], class: "input-small filter" %>
          <%  end %>
          <a href="#" class="btn btn-small add-on" onclick="$(this.previousElementSibling).val('');return false;">x</a>
        </div>
      <% end %>
    </td>

app/views/contracts/_filter_fields.html.erb
<%= render "filter_field", locals: {p1: "fnumber"}, s: s %>
<%= render "filter_field", locals: {p1: "fdate_f", p2: "fdate_l"}, s: s %>
<%= render "filter_field", locals: {p1: "fdatestart_f", p2: "fdatestart_l"}, s: s %>
<%= render "filter_field", locals: {p1: "fdatefinish_f", p2: "fdatefinish_l"}, s: s %>
<%= render "filter_field", locals: {p1: "finsurant_name"}, s: s %>
<%= render "filter_field", locals: {p1: "finsured_name"}, s: s %>
<%= render "filter_field", locals: {p1: "fcost"}, s: s %>
<%= render "filter_field", locals: {p1: "ikp"}, s: s %>

app/views/contracts/_filter_form.html.erb
<tr id="filter-row" class="filter-row">
  <%= form_tag contracts_save_filter_path, method: "post" do %>
    <%= render "filter_fields", s: @session %>
  <td>
      <%= submit_tag "Apply filter", class: "btn btn-small" %>
  <% end %>
  <%= form_tag contracts_clear_filter_path, method: "post" do %>
    <%= submit_tag "Clear filter", class: "btn btn-small" %>
  <% end %>
  </td>
</tr>

app/views/contracts/_people_fields.html.erb
    <div class="span4">
      <strong>Strahovatel:</strong>
      <div id="insurant_fields" class="well">
      </div>
    </div>
    <div class="span4">
      <strong>Zastrahovanniy:</strong>
      <div id="insured_fields" class="well">
      </div>
    </div>

app/views/contracts/edit.html.erb
<h1>Edit policy: <%= @contract.number %> </h1>

<div class="row">

  <div class="span4">
    <strong>Information about policy</strong>
    <div id="policy_fields" class="well">
      <%= form_for(@contract) do |f| %>
        <%= render 'contract_fields', f: f %>
        <%= f.submit "Save changes", tabindex: 100, class: "btn btn-large btn-primary" %>
        <% end %>
      </div>
    </div>

  <%= render 'people_fields' %>
  </div>

app/views/contracts/index.html.erb
<div id="filter">
  
</div>
<h1>Policies</h1>

<table class="table table-bordered table-striped">
  <tr>
    <th><%= t "contract.view.index.number" %></th>
    <th><%= t("contract.view.index.date") %></th>
    <th><%= t("contract.view.index.date_start") %></th>
    <th><%= t("contract.view.index.date_finish") %></th>
    <th><%= t("contract.view.index.insurant") %></th>
    <th><%= t("contract.view.index.insured") %></th>
    <th><%= t("contract.view.index.cost") %></th>
    <th><%= t("contract.view.index.ikp") %></th>
    <th></th>
  </tr>
  <%= render "filter_form", s: @session   %>
 
<%= render @contracts %>

</table>
<%= will_paginate %>
<br>
 
<%= link_to "New policy", new_contract_path %>

app/views/contracts/new.html.erb
<h1>New policy:</h1>

<div class="row">

  <div class="span4">
    <strong>Information about policy</strong>
    <div id="policy_fields" class="well">
      <%= form_for(@contract) do |f| %>
        <%= render 'contract_fields', f: f %>
        <%= f.submit "Save new policy", tabindex: 100, class: "btn btn-large btn-primary" %>
        <% end %>
      </div>
    </div>

  <%= render 'people_fields' %>
  </div>