config/routes.rb
Tp::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registration' }

  
  get "/" => 'contracts#index'

  get "people/search" => 'people#search'
  get ':controller/validate', action: 'validate', as: :validate_form
  get "people/get_new_view" => 'people#get_new_view'
  get "organizations/search" => 'organizations#search'
  post "contracts/save_filter" => 'contracts#save_filter'
  post "contracts/clear_filter" => 'contracts#clear_filter'
  get "contracts/print/:id" => 'contracts#print', as: :contract_print
  resources :contracts
  resources :organizations
  resources :people
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :people
  has_many :contracts, :through => :people
  has_many :users, -> {uniq}, through: :contracts
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  
  def index
    if current_user.nil?
      @organizations=Organization.paginate(page: params[:page], 
                                               per_page: 10)
    else
      @organizations=current_user.organizations.paginate(page: params[:page],
                                               per_page: 10)
    end
  end
  
  def search
    request='%'+params[:name]+'%'
    @res=Organization.select(:id,:name).where("name LIKE ?",request)
    respond_to do |format|
      format.html {render "404"}
      format.json {render json: @res}
    end
  end
  
  def new
    @organization=Organization.new
  end
  
  def create
    @organization=Organization.new(organization_params)
    if @organization.save
      flash[:success]= 'Organization added successfully!'
      redirect_to(organizations_path)
    else
      render 'new'
    end
  end
  
  def edit
    @organization=Organization.find(params[:id])
  end
  
  def update
    @organization=Organization.find(params[:id])
    if @organization.update_attributes(organization_params)
      flash[:success]="Organization updated successfully"
      redirect_to(organizations_path)
    else
      render 'edit'
    end
  end
  
  def destroy
    @organization=Organization.find(params[:id])
    if @organization.people.count==0
      if @organization.destroy
        flash[:success]="Organization deleted"
      else
        flash[:error]="Error while deleting organization"
      end
    else
      flash[:error]="Deleting unsuccessfull (workers>0)"
    end
    redirect_to(organizations_path)
  end
  
  private
  
    def organization_params
      params.require(:organization).permit(:name)
    end
end

app/views/organizations/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="well">
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
</div>

app/views/organizations/_organization.html.erb
<tr>
    <td><%= organization.name %></td>
    <td><%= link_to organization.people.count, "#", class: "btn" %></td>
    <td>
      <%= link_to "Edit", edit_organization_path(organization), class: "btn" %>
      <% if organization.people.count == 0 %> 
        <%=  link_to "Remove", organization, method: :delete, class: "btn", data: { confirm: "Are you sure?" } %>
      <% end %>    
    </td>
</tr>

app/views/organizations/city.html.erb
<div class="ui-widget">
  <label for="city">Город: </label><input id="city" /><br />
  <span style="font-size:.8em;">Поддерживается <a href="http://geonames.org">geonames.org</a></span>
</div>
<div id="log" class="ui-widget ui-widget-content"></div>

app/views/organizations/edit.html.erb
<h1>Edit Organization</h1>

<div class="row">
  <div>
    <%= form_for(@organization) do |f| %>
      
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
    
    <% @organization.people.each do |p| %>
    <p><%=p.firstname%> <%=p.lastname%></p>
    <% end %>
  </div>
</div>

app/views/organizations/index.html.erb
<h1>Organizations</h1>

<table class="table table-bordered table-striped">
  <tr>
    <th>Name</th>
    <th>Workers count</th>
    <th></th>
  </tr>
 
<%= render @organizations %>

</table>
<%= will_paginate %>
<br>
 
<%= link_to "Add organization", new_organization_path, class: "btn" %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<div class="row">
  <div>
    <%= form_for(@organization) do |f| %>
      
      <%= render 'fields', f: f %>
      <%= f.submit "Save organization", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>